export const siteConfig = {
  domain: "bedarfsanalyse-ki.de",
  siteName: "Bedarfsanalyse KI",
  tagline:
    "Finden Sie in 5 Minuten heraus, wo Ihr Unternehmen beim Einsatz von KI steht — mit unserer kostenlosen Bedarfsanalyse.",
  description:
    "Kostenlose Bedarfsanalyse KI für Unternehmen. Ermitteln Sie Ihren KI-Reifegrad, identifizieren Sie Automatisierungspotenziale und erhalten Sie sofort umsetzbare Handlungsempfehlungen.",
  niche: "general",
  nicheLabel: "Unternehmen",
  nicheDescription: "Entscheider, Geschäftsführer und Abteilungsleiter",
  seo: {
    title: "Bedarfsanalyse KI | Kostenloser KI Readiness Check für Unternehmen",
    description:
      "Kostenlose KI Bedarfsanalyse für Ihr Unternehmen. In 5 Minuten KI-Reifegrad ermitteln, Einsparpotenziale berechnen und konkrete Handlungsempfehlungen erhalten. Von Experten entwickelt.",
    keywords: [
      "Bedarfsanalyse KI",
      "KI Bedarfsanalyse",
      "KI Bedarfsanalyse Unternehmen",
      "KI Readiness Check",
      "KI Reifegrad",
      "KI Potenzialanalyse",
      "KI Status Quo Analyse",
      "Künstliche Intelligenz Bedarfsermittlung",
      "KI Strategie Check",
      "KI Beratung Mittelstand",
      "KI Readiness",
      "Digitalisierung KI Test",
      "Prozessoptimierung KI",
    ],
  },
  author: {
    name: "Tobias Gossmann",
    role: "Geschäftsführer & KI-Stratege",
    company: "famefact | track by track GmbH",
    linkedin: "https://www.linkedin.com/in/tobias-famefact/",
    bio: "Tobias Gossmann ist Geschäftsführer der track by track GmbH und Gründer von famefact — einer der führenden Agenturen für KI-gestützte Unternehmensprozesse in Deutschland. Mit über 10 Jahren Erfahrung in digitaler Transformation berät er mittelständische Unternehmen, Konzerne und öffentliche Einrichtungen bei der strategischen Einführung von Künstlicher Intelligenz.",
  },
  colors: {
    primary: "#0D0D0D",
    accent: "#bbd8a7",
    iris: "#a387c1",
  },
  legal: {
    companyName: "track by track GmbH",
    street: "Schliemannstraße 23",
    zip: "10437",
    city: "Berlin",
    country: "Deutschland",
    phone: "+49 30 403 6654 30",
    email: "info@trackbytrack.de",
    managingDirector: "Gorden Allgemein",
    registerCourt: "Amtsgericht Berlin-Charlottenburg",
    registerNumber: "HRB XXXXX",
    vatId: "DE XXXXXXXXX",
    responsibleContent: "Gorden Allgemein",
  },
  scoring: {
    maturityLevels: [
      { min: 0, max: 20, label: "KI-Einsteiger", emoji: "🌱", level: 1 },
      { min: 21, max: 40, label: "KI-Experimentierer", emoji: "🔬", level: 2 },
      { min: 41, max: 60, label: "KI-Nutzer", emoji: "⚙️", level: 3 },
      { min: 61, max: 80, label: "KI-Integriert", emoji: "🚀", level: 4 },
      { min: 81, max: 100, label: "KI-First", emoji: "🏆", level: 5 },
    ],
  },
  cta: {
    primary: "Jetzt Bedarfsanalyse starten",
    calendly: "https://calendly.com/trackbytrack/ki-beratung",
  },
};
