export const siteConfig = {
  domain: "ki-beratung-kmu.de",
  siteName: "KI Beratung KMU",
  tagline:
    "Professionelle KI Beratung für den Mittelstand — mit kostenlosem Readiness Check in 5 Minuten.",
  description:
    "KI Beratung für KMU und Mittelstand. Kostenloser KI-Readiness Check: Erfahren Sie Ihren KI-Reifegrad, entdecken Sie Automatisierungspotenziale und erhalten Sie konkrete Handlungsempfehlungen für die KI-Einführung in Ihrem Unternehmen.",
  niche: "general",
  nicheLabel: "KMU & Mittelstand",
  nicheDescription: "Geschäftsführer, Entscheider und Abteilungsleiter in kleinen und mittelständischen Unternehmen",
  seo: {
    title: "KI Beratung KMU | Kostenloser KI-Readiness Check für den Mittelstand",
    description:
      "KI Beratung speziell für KMU und Mittelstand. Kostenloser KI-Readiness Check in 5 Minuten: KI-Reifegrad erfahren, Einsparpotenziale berechnen, konkrete Empfehlungen erhalten. Von Experten entwickelt.",
    keywords: [
      "KI Beratung KMU",
      "KI Beratung Mittelstand",
      "KI Readiness Check",
      "KI Reifegrad",
      "Künstliche Intelligenz Beratung",
      "KI Strategie Unternehmen",
      "KI Einführung Mittelstand",
      "KI Potenzialanalyse",
      "KI für kleine Unternehmen",
      "KI Automatisierung KMU",
      "Digitalisierung KMU",
      "KI Check Unternehmen",
      "KI Beratung Deutschland",
      "Prozessoptimierung KI",
    ],
  },
  author: {
    name: "Tobias Sander",
    role: "Geschäftsführer & KI-Strategieberater",
    company: "famefact | track by track GmbH",
    linkedin: "https://www.linkedin.com/in/tobias-famefact/",
    bio: "Tobias Sander ist Geschäftsführer der track by track GmbH und Gründer von famefact — einer der führenden Agenturen für KI-gestützte Unternehmensprozesse in Deutschland. Mit über 10 Jahren Erfahrung in digitaler Transformation berät er mittelständische Unternehmen, Konzerne und öffentliche Institutionen bei der strategischen Einführung von Künstlicher Intelligenz.",
  },
  colors: {
    primary: "#0D0D0D",
    accent: "#bbd8a7",
    iris: "#a387c1",
  },
  legal: {
    companyName: "track by track GmbH",
    street: "Schliemannstraße 23",
    zip: "10437",
    city: "Berlin",
    country: "Deutschland",
    phone: "+49 30 403 6654 30",
    email: "info@trackbytrack.de",
    managingDirector: "Tobias Sander",
    registerCourt: "Amtsgericht Berlin-Charlottenburg",
    registerNumber: "HRB XXXXX",
    vatId: "DE XXXXXXXXX",
    responsibleContent: "Tobias Sander",
  },
  scoring: {
    maturityLevels: [
      { min: 0, max: 20, label: "KI-Einsteiger", emoji: "🌱", level: 1 },
      { min: 21, max: 40, label: "KI-Experimentierer", emoji: "🔬", level: 2 },
      { min: 41, max: 60, label: "KI-Nutzer", emoji: "⚙️", level: 3 },
      { min: 61, max: 80, label: "KI-Integriert", emoji: "🚀", level: 4 },
      { min: 81, max: 100, label: "KI-First", emoji: "🏆", level: 5 },
    ],
  },
  cta: {
    primary: "Jetzt KI-Check starten",
    calendly: "https://calendly.com/trackbytrack/ki-beratung",
  },
};
